### ISSUE TITLE
Always getting skipping message

### ISSUE THREAD

**Issue by wintercounter** [alexindigo/install-peers-cli#5]
`Only run install-peer-deps after \`install\` command. Skipping.`

No matther what I do. The instructions are pretty straightforward.
I get the same message both after normal `npm install` or `npm run install-peers`.

Windows 10
Node 11

**Comment by juliaqiuxy** [comment]
You probably would want to include `install-peers` in `postinstall` instead of running it by itself. If not, you can also use `-f` to force the install (only available >= 2.1.1).

**Comment by jdnichollsc** [comment]
Hi @juliaqiuxy, is it possible to use from `prepare` script? I want to use it to install my peer dependencies in order to debug my package without put these as devDependencies too
